// flow-typed signature: f56dce74dace4deac0d7e6332caffa9d
// flow-typed version: <<STUB>>/erebos-api-bzz-node_v*/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'erebos-api-bzz-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'erebos-api-bzz-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'erebos-api-bzz-node/flow-typed/npm/erebos-api-bzz-base_vx.x.x' {
  declare module.exports: any;
}

declare module 'erebos-api-bzz-node/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'erebos-api-bzz-node/flow-typed/npm/node-fetch_vx.x.x' {
  declare module.exports: any;
}

declare module 'erebos-api-bzz-node/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'erebos-api-bzz-node/flow-typed/npm/erebos-api-bzz-base_vx.x.x.js' {
  declare module.exports: $Exports<'erebos-api-bzz-node/flow-typed/npm/erebos-api-bzz-base_vx.x.x'>;
}
declare module 'erebos-api-bzz-node/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'erebos-api-bzz-node/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'erebos-api-bzz-node/flow-typed/npm/node-fetch_vx.x.x.js' {
  declare module.exports: $Exports<'erebos-api-bzz-node/flow-typed/npm/node-fetch_vx.x.x'>;
}
declare module 'erebos-api-bzz-node/src/index.js' {
  declare module.exports: $Exports<'erebos-api-bzz-node/src/index'>;
}
