// flow-typed signature: 8b0a5e2c45947d9c0568348634f7dc45
// flow-typed version: <<STUB>>/@oclif/command_v^1.5.13/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oclif/command'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oclif/command' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oclif/command/flush' {
  declare module.exports: any;
}

declare module '@oclif/command/lib/command' {
  declare module.exports: any;
}

declare module '@oclif/command/lib/flags' {
  declare module.exports: any;
}

declare module '@oclif/command/lib/index' {
  declare module.exports: any;
}

declare module '@oclif/command/lib/main' {
  declare module.exports: any;
}

declare module '@oclif/command/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oclif/command/flush.js' {
  declare module.exports: $Exports<'@oclif/command/flush'>;
}
declare module '@oclif/command/lib/command.js' {
  declare module.exports: $Exports<'@oclif/command/lib/command'>;
}
declare module '@oclif/command/lib/flags.js' {
  declare module.exports: $Exports<'@oclif/command/lib/flags'>;
}
declare module '@oclif/command/lib/index.js' {
  declare module.exports: $Exports<'@oclif/command/lib/index'>;
}
declare module '@oclif/command/lib/main.js' {
  declare module.exports: $Exports<'@oclif/command/lib/main'>;
}
declare module '@oclif/command/lib/util.js' {
  declare module.exports: $Exports<'@oclif/command/lib/util'>;
}
