// flow-typed signature: 60a659f9d7f73b388c5d090366358223
// flow-typed version: <<STUB>>/@oclif/config_v^1.10.4/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oclif/config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oclif/config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oclif/config/lib/command' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/config' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/debug' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/hooks' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/index' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/manifest' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/pjson' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/plugin' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/screen' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/topic' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/ts-node' {
  declare module.exports: any;
}

declare module '@oclif/config/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oclif/config/lib/command.js' {
  declare module.exports: $Exports<'@oclif/config/lib/command'>;
}
declare module '@oclif/config/lib/config.js' {
  declare module.exports: $Exports<'@oclif/config/lib/config'>;
}
declare module '@oclif/config/lib/debug.js' {
  declare module.exports: $Exports<'@oclif/config/lib/debug'>;
}
declare module '@oclif/config/lib/hooks.js' {
  declare module.exports: $Exports<'@oclif/config/lib/hooks'>;
}
declare module '@oclif/config/lib/index.js' {
  declare module.exports: $Exports<'@oclif/config/lib/index'>;
}
declare module '@oclif/config/lib/manifest.js' {
  declare module.exports: $Exports<'@oclif/config/lib/manifest'>;
}
declare module '@oclif/config/lib/pjson.js' {
  declare module.exports: $Exports<'@oclif/config/lib/pjson'>;
}
declare module '@oclif/config/lib/plugin.js' {
  declare module.exports: $Exports<'@oclif/config/lib/plugin'>;
}
declare module '@oclif/config/lib/screen.js' {
  declare module.exports: $Exports<'@oclif/config/lib/screen'>;
}
declare module '@oclif/config/lib/topic.js' {
  declare module.exports: $Exports<'@oclif/config/lib/topic'>;
}
declare module '@oclif/config/lib/ts-node.js' {
  declare module.exports: $Exports<'@oclif/config/lib/ts-node'>;
}
declare module '@oclif/config/lib/util.js' {
  declare module.exports: $Exports<'@oclif/config/lib/util'>;
}
