// flow-typed signature: cfe67288bafc737dcf3f58e2ac2fe29f
// flow-typed version: <<STUB>>/@oclif/plugin-help_v^2.1.3/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oclif/plugin-help'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oclif/plugin-help' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oclif/plugin-help/lib/command' {
  declare module.exports: any;
}

declare module '@oclif/plugin-help/lib/commands/help' {
  declare module.exports: any;
}

declare module '@oclif/plugin-help/lib/index' {
  declare module.exports: any;
}

declare module '@oclif/plugin-help/lib/list' {
  declare module.exports: any;
}

declare module '@oclif/plugin-help/lib/root' {
  declare module.exports: any;
}

declare module '@oclif/plugin-help/lib/screen' {
  declare module.exports: any;
}

declare module '@oclif/plugin-help/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oclif/plugin-help/lib/command.js' {
  declare module.exports: $Exports<'@oclif/plugin-help/lib/command'>;
}
declare module '@oclif/plugin-help/lib/commands/help.js' {
  declare module.exports: $Exports<'@oclif/plugin-help/lib/commands/help'>;
}
declare module '@oclif/plugin-help/lib/index.js' {
  declare module.exports: $Exports<'@oclif/plugin-help/lib/index'>;
}
declare module '@oclif/plugin-help/lib/list.js' {
  declare module.exports: $Exports<'@oclif/plugin-help/lib/list'>;
}
declare module '@oclif/plugin-help/lib/root.js' {
  declare module.exports: $Exports<'@oclif/plugin-help/lib/root'>;
}
declare module '@oclif/plugin-help/lib/screen.js' {
  declare module.exports: $Exports<'@oclif/plugin-help/lib/screen'>;
}
declare module '@oclif/plugin-help/lib/util.js' {
  declare module.exports: $Exports<'@oclif/plugin-help/lib/util'>;
}
