// flow-typed signature: 1077615a08f984b381254ef80232284d
// flow-typed version: <<STUB>>/@types/bn.js_v^4.11.4/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/bn.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/bn.js' {
  declare module.exports: any;
}
