// flow-typed signature: eed835636ad3a6dd8bfae97bd131b6ac
// flow-typed version: <<STUB>>/@types/bn.js_v^4.11.5/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/bn.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/bn.js' {
  declare module.exports: any;
}
