// flow-typed signature: 008371d63cc625e7eba814d12ae0408b
// flow-typed version: <<STUB>>/@types/chai_v4.1.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chai' {
  declare module.exports: any;
}
