// flow-typed signature: 0bbd2bd67a3ea02e449d34f76e74a983
// flow-typed version: <<STUB>>/@types/elliptic_v^6.4.8/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/elliptic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/elliptic' {
  declare module.exports: any;
}
