// flow-typed signature: 3c2c6b797cb64d6175fae99f199e04a8
// flow-typed version: <<STUB>>/@types/mocha_v2.2.48/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mocha' {
  declare module.exports: any;
}
