// flow-typed signature: 84c06ff084945e6564e4c543538dc981
// flow-typed version: <<STUB>>/@types/node-fetch_v^2.1.4/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node-fetch' {
  declare module.exports: any;
}
