// flow-typed signature: bf83857695a9ec78abaa96f2efa29407
// flow-typed version: <<STUB>>/@types/node_v9.4.5/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
