// flow-typed signature: 92cac065cd614dd30abc4b562a9f2e87
// flow-typed version: <<STUB>>/@types/node-fetch_v^2.1.6/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node-fetch' {
  declare module.exports: any;
}
