// flow-typed signature: c55de2c88bd399929595ad2a4d6fd4ef
// flow-typed version: <<STUB>>/@types/sinon-chai_v2.7.29/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/sinon-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/sinon-chai' {
  declare module.exports: any;
}
