// flow-typed signature: eb0b77fb924e86d38008a03decc4f79f
// flow-typed version: <<STUB>>/@types/sinon_v4.1.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/sinon' {
  declare module.exports: any;
}
