// flow-typed signature: 4c41796f8029764dee1fd1aefcc17730
// flow-typed version: <<STUB>>/@types/source-map_v^0.5.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/source-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/source-map' {
  declare module.exports: any;
}
