// flow-typed signature: 5b36bae8c622c94f6df2d1d5f7cb84c4
// flow-typed version: <<STUB>>/automerge_v^0.10.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'automerge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'automerge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'automerge/backend/index' {
  declare module.exports: any;
}

declare module 'automerge/backend/op_set' {
  declare module.exports: any;
}

declare module 'automerge/backend/skip_list' {
  declare module.exports: any;
}

declare module 'automerge/dist/automerge' {
  declare module.exports: any;
}

declare module 'automerge/frontend/apply_patch' {
  declare module.exports: any;
}

declare module 'automerge/frontend/constants' {
  declare module.exports: any;
}

declare module 'automerge/frontend/context' {
  declare module.exports: any;
}

declare module 'automerge/frontend/counter' {
  declare module.exports: any;
}

declare module 'automerge/frontend/index' {
  declare module.exports: any;
}

declare module 'automerge/frontend/proxies' {
  declare module.exports: any;
}

declare module 'automerge/frontend/table' {
  declare module.exports: any;
}

declare module 'automerge/frontend/text' {
  declare module.exports: any;
}

declare module 'automerge/karma.conf' {
  declare module.exports: any;
}

declare module 'automerge/karma.sauce' {
  declare module.exports: any;
}

declare module 'automerge/src/automerge' {
  declare module.exports: any;
}

declare module 'automerge/src/common' {
  declare module.exports: any;
}

declare module 'automerge/src/connection' {
  declare module.exports: any;
}

declare module 'automerge/src/doc_set' {
  declare module.exports: any;
}

declare module 'automerge/src/uuid' {
  declare module.exports: any;
}

declare module 'automerge/src/watchable_doc' {
  declare module.exports: any;
}

declare module 'automerge/test/backend_test' {
  declare module.exports: any;
}

declare module 'automerge/test/connection_test' {
  declare module.exports: any;
}

declare module 'automerge/test/frontend_test' {
  declare module.exports: any;
}

declare module 'automerge/test/helpers' {
  declare module.exports: any;
}

declare module 'automerge/test/proxies_test' {
  declare module.exports: any;
}

declare module 'automerge/test/skip_list_test' {
  declare module.exports: any;
}

declare module 'automerge/test/table_test' {
  declare module.exports: any;
}

declare module 'automerge/test/test_uuid' {
  declare module.exports: any;
}

declare module 'automerge/test/test' {
  declare module.exports: any;
}

declare module 'automerge/test/text_test' {
  declare module.exports: any;
}

declare module 'automerge/test/watchable_doc_test' {
  declare module.exports: any;
}

declare module 'automerge/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'automerge/backend/index.js' {
  declare module.exports: $Exports<'automerge/backend/index'>;
}
declare module 'automerge/backend/op_set.js' {
  declare module.exports: $Exports<'automerge/backend/op_set'>;
}
declare module 'automerge/backend/skip_list.js' {
  declare module.exports: $Exports<'automerge/backend/skip_list'>;
}
declare module 'automerge/dist/automerge.js' {
  declare module.exports: $Exports<'automerge/dist/automerge'>;
}
declare module 'automerge/frontend/apply_patch.js' {
  declare module.exports: $Exports<'automerge/frontend/apply_patch'>;
}
declare module 'automerge/frontend/constants.js' {
  declare module.exports: $Exports<'automerge/frontend/constants'>;
}
declare module 'automerge/frontend/context.js' {
  declare module.exports: $Exports<'automerge/frontend/context'>;
}
declare module 'automerge/frontend/counter.js' {
  declare module.exports: $Exports<'automerge/frontend/counter'>;
}
declare module 'automerge/frontend/index.js' {
  declare module.exports: $Exports<'automerge/frontend/index'>;
}
declare module 'automerge/frontend/proxies.js' {
  declare module.exports: $Exports<'automerge/frontend/proxies'>;
}
declare module 'automerge/frontend/table.js' {
  declare module.exports: $Exports<'automerge/frontend/table'>;
}
declare module 'automerge/frontend/text.js' {
  declare module.exports: $Exports<'automerge/frontend/text'>;
}
declare module 'automerge/karma.conf.js' {
  declare module.exports: $Exports<'automerge/karma.conf'>;
}
declare module 'automerge/karma.sauce.js' {
  declare module.exports: $Exports<'automerge/karma.sauce'>;
}
declare module 'automerge/src/automerge.js' {
  declare module.exports: $Exports<'automerge/src/automerge'>;
}
declare module 'automerge/src/common.js' {
  declare module.exports: $Exports<'automerge/src/common'>;
}
declare module 'automerge/src/connection.js' {
  declare module.exports: $Exports<'automerge/src/connection'>;
}
declare module 'automerge/src/doc_set.js' {
  declare module.exports: $Exports<'automerge/src/doc_set'>;
}
declare module 'automerge/src/uuid.js' {
  declare module.exports: $Exports<'automerge/src/uuid'>;
}
declare module 'automerge/src/watchable_doc.js' {
  declare module.exports: $Exports<'automerge/src/watchable_doc'>;
}
declare module 'automerge/test/backend_test.js' {
  declare module.exports: $Exports<'automerge/test/backend_test'>;
}
declare module 'automerge/test/connection_test.js' {
  declare module.exports: $Exports<'automerge/test/connection_test'>;
}
declare module 'automerge/test/frontend_test.js' {
  declare module.exports: $Exports<'automerge/test/frontend_test'>;
}
declare module 'automerge/test/helpers.js' {
  declare module.exports: $Exports<'automerge/test/helpers'>;
}
declare module 'automerge/test/proxies_test.js' {
  declare module.exports: $Exports<'automerge/test/proxies_test'>;
}
declare module 'automerge/test/skip_list_test.js' {
  declare module.exports: $Exports<'automerge/test/skip_list_test'>;
}
declare module 'automerge/test/table_test.js' {
  declare module.exports: $Exports<'automerge/test/table_test'>;
}
declare module 'automerge/test/test_uuid.js' {
  declare module.exports: $Exports<'automerge/test/test_uuid'>;
}
declare module 'automerge/test/test.js' {
  declare module.exports: $Exports<'automerge/test/test'>;
}
declare module 'automerge/test/text_test.js' {
  declare module.exports: $Exports<'automerge/test/text_test'>;
}
declare module 'automerge/test/watchable_doc_test.js' {
  declare module.exports: $Exports<'automerge/test/watchable_doc_test'>;
}
declare module 'automerge/webpack.config.js' {
  declare module.exports: $Exports<'automerge/webpack.config'>;
}
