// flow-typed signature: 92bac57e3d08303dd419ef257c62fe1a
// flow-typed version: <<STUB>>/chai_v4.1.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai' {
  declare module.exports: any;
}
