// flow-typed signature: 01d5fcb334589809326a1ab2001c7a1c
// flow-typed version: <<STUB>>/chai_v^3.5.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai' {
  declare module.exports: any;
}
