// flow-typed signature: 0fcd4edb143190e871019939a0105ea9
// flow-typed version: <<STUB>>/color_v3.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color' {
  declare module.exports: any;
}
