// flow-typed signature: 536b63f2e851e7f1a32dfd756922ef88
// flow-typed version: <<STUB>>/color_v^0.11.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color' {
  declare module.exports: any;
}
