// flow-typed signature: 8a7f12d7db4311ab7b79be0a1055ad30
// flow-typed version: <<STUB>>/colors_v1.1.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'colors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'colors' {
  declare module.exports: any;
}
