// flow-typed signature: 27115350f21cb3c4c82742f4554a58cb
// flow-typed version: <<STUB>>/commitizen_v2.9.6/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commitizen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commitizen' {
  declare module.exports: any;
}
