// flow-typed signature: 31689f5d0c0731c3f2512a0e8657a440
// flow-typed version: <<STUB>>/commitizen_v^2.8.6/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commitizen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commitizen' {
  declare module.exports: any;
}
