// flow-typed signature: 69f00a3e2740c6bb994fcd647a1691d6
// flow-typed version: <<STUB>>/coveralls_v^2.11.13/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coveralls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coveralls' {
  declare module.exports: any;
}
