// flow-typed signature: e8fa8adfdbbfea59dbc8bca49ff6ef20
// flow-typed version: <<STUB>>/coveralls_v3.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coveralls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coveralls' {
  declare module.exports: any;
}
