// flow-typed signature: e4915af3c53f79e4cb5015b360a18c20
// flow-typed version: <<STUB>>/cz-conventional-changelog_v1.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-conventional-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-conventional-changelog' {
  declare module.exports: any;
}
