// flow-typed signature: ba4e995004990e4ef2e154e9a3f70f1f
// flow-typed version: <<STUB>>/cz-conventional-changelog_v^1.2.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-conventional-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-conventional-changelog' {
  declare module.exports: any;
}
