// flow-typed signature: f363b2f43e30d3c28fcb42f55bd2ae7a
// flow-typed version: <<STUB>>/danger_v^1.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger' {
  declare module.exports: any;
}
