// flow-typed signature: ee1314975f3a59839f5db8fb025b136c
// flow-typed version: <<STUB>>/danger_v1.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger' {
  declare module.exports: any;
}
