// flow-typed signature: a3aa84d075b248d2b16c64b5e08d18d5
// flow-typed version: <<STUB>>/dependency-cruiser_v2.13.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dependency-cruiser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dependency-cruiser' {
  declare module.exports: any;
}
