// flow-typed signature: 6686ddb5c4939e4ad1bbc32260b8bdae
// flow-typed version: <<STUB>>/doctoc_v^1.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'doctoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'doctoc' {
  declare module.exports: any;
}
