// flow-typed signature: 78a7f205613367b8d1ca583ff4d2006f
// flow-typed version: <<STUB>>/doctoc_v1.3.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'doctoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'doctoc' {
  declare module.exports: any;
}
