// flow-typed signature: adfe149f111584aa78c3cdf8c305fc30
// flow-typed version: <<STUB>>/escape-string-regexp_v1.0.5/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'escape-string-regexp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'escape-string-regexp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'escape-string-regexp/index' {
  declare module.exports: $Exports<'escape-string-regexp'>;
}
declare module 'escape-string-regexp/index.js' {
  declare module.exports: $Exports<'escape-string-regexp'>;
}
