// flow-typed signature: 589305ba077758a844ffb499a7bd6ad3
// flow-typed version: <<STUB>>/esdoc_v^0.4.7/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc' {
  declare module.exports: any;
}
