// flow-typed signature: d1fdfcfcfc1d7b32d8dbf0ea3e1aa130
// flow-typed version: <<STUB>>/esdoc_v0.4.7/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc' {
  declare module.exports: any;
}
