// flow-typed signature: 3f1fe3aceb2f18833fd4fcff2324d241
// flow-typed version: <<STUB>>/eslint_v^3.8.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
