// flow-typed signature: 14f7a25aefa21e36ee9fc828cd9bba90
// flow-typed version: <<STUB>>/get-folder-size_v^1.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-folder-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-folder-size' {
  declare module.exports: any;
}
