// flow-typed signature: 7dc65161ac68def1f63e9f9fa3de6e8f
// flow-typed version: <<STUB>>/gm_v^1.22.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gm' {
  declare module.exports: any;
}
