// flow-typed signature: cc75f3c946ba30762f9ed249f3a7da39
// flow-typed version: <<STUB>>/gm_v1.23.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gm' {
  declare module.exports: any;
}
