// flow-typed signature: 52dedb9b47db224ae6ab9db3c779502c
// flow-typed version: <<STUB>>/google-closure-compiler-js_v^20170218.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'google-closure-compiler-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'google-closure-compiler-js' {
  declare module.exports: any;
}
