// flow-typed signature: 04efa48caf7c58669a739dd62c95e5e1
// flow-typed version: <<STUB>>/gzip-size_v4.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gzip-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gzip-size' {
  declare module.exports: any;
}
