// flow-typed signature: 71ce5874f89a4e1016f339709253f422
// flow-typed version: <<STUB>>/http-server_v0.11.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-server' {
  declare module.exports: any;
}
