// flow-typed signature: fc52d516c6536b350a8eef5386381b7f
// flow-typed version: <<STUB>>/http-server_v^0.9.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-server' {
  declare module.exports: any;
}
