// flow-typed signature: e85d15c69c9936dbc690194473b1ad87
// flow-typed version: <<STUB>>/husky_v^0.13.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'husky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'husky' {
  declare module.exports: any;
}
