// flow-typed signature: aec9eccd2b5a66187560b4e81e461074
// flow-typed version: <<STUB>>/husky_v0.14.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'husky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'husky' {
  declare module.exports: any;
}
