// flow-typed signature: 1fc1b61c673a8f4bed703b56a671b2d7
// flow-typed version: <<STUB>>/klaw-sync_v3.0.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'klaw-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'klaw-sync' {
  declare module.exports: any;
}
