// flow-typed signature: b54a13a7825c14f857b031112a08903a
// flow-typed version: <<STUB>>/klaw-sync_v^3.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'klaw-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'klaw-sync' {
  declare module.exports: any;
}
