// flow-typed signature: 310741e3bde58835889c74bf542f1162
// flow-typed version: <<STUB>>/lint-staged_v3.2.5/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lint-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lint-staged' {
  declare module.exports: any;
}
