// flow-typed signature: 52f3799192398ff5a04ed09891843023
// flow-typed version: <<STUB>>/madge_v^1.4.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'madge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'madge' {
  declare module.exports: any;
}
