// flow-typed signature: 2700fd695eaf09909c98c6cee191ce7c
// flow-typed version: <<STUB>>/markdown-doctest_v^0.9.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-doctest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-doctest' {
  declare module.exports: any;
}
