// flow-typed signature: 45e4c7885b7a246673077a9f1a7dd0f8
// flow-typed version: <<STUB>>/markdown-doctest_v0.9.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-doctest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-doctest' {
  declare module.exports: any;
}
