// flow-typed signature: 0eba06168b951ff799dd70974ffc0c1f
// flow-typed version: <<STUB>>/minimist_v1.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minimist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minimist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minimist/example/parse' {
  declare module.exports: any;
}

declare module 'minimist/test/all_bool' {
  declare module.exports: any;
}

declare module 'minimist/test/bool' {
  declare module.exports: any;
}

declare module 'minimist/test/dash' {
  declare module.exports: any;
}

declare module 'minimist/test/default_bool' {
  declare module.exports: any;
}

declare module 'minimist/test/dotted' {
  declare module.exports: any;
}

declare module 'minimist/test/kv_short' {
  declare module.exports: any;
}

declare module 'minimist/test/long' {
  declare module.exports: any;
}

declare module 'minimist/test/num' {
  declare module.exports: any;
}

declare module 'minimist/test/parse_modified' {
  declare module.exports: any;
}

declare module 'minimist/test/parse' {
  declare module.exports: any;
}

declare module 'minimist/test/short' {
  declare module.exports: any;
}

declare module 'minimist/test/stop_early' {
  declare module.exports: any;
}

declare module 'minimist/test/unknown' {
  declare module.exports: any;
}

declare module 'minimist/test/whitespace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minimist/example/parse.js' {
  declare module.exports: $Exports<'minimist/example/parse'>;
}
declare module 'minimist/index' {
  declare module.exports: $Exports<'minimist'>;
}
declare module 'minimist/index.js' {
  declare module.exports: $Exports<'minimist'>;
}
declare module 'minimist/test/all_bool.js' {
  declare module.exports: $Exports<'minimist/test/all_bool'>;
}
declare module 'minimist/test/bool.js' {
  declare module.exports: $Exports<'minimist/test/bool'>;
}
declare module 'minimist/test/dash.js' {
  declare module.exports: $Exports<'minimist/test/dash'>;
}
declare module 'minimist/test/default_bool.js' {
  declare module.exports: $Exports<'minimist/test/default_bool'>;
}
declare module 'minimist/test/dotted.js' {
  declare module.exports: $Exports<'minimist/test/dotted'>;
}
declare module 'minimist/test/kv_short.js' {
  declare module.exports: $Exports<'minimist/test/kv_short'>;
}
declare module 'minimist/test/long.js' {
  declare module.exports: $Exports<'minimist/test/long'>;
}
declare module 'minimist/test/num.js' {
  declare module.exports: $Exports<'minimist/test/num'>;
}
declare module 'minimist/test/parse_modified.js' {
  declare module.exports: $Exports<'minimist/test/parse_modified'>;
}
declare module 'minimist/test/parse.js' {
  declare module.exports: $Exports<'minimist/test/parse'>;
}
declare module 'minimist/test/short.js' {
  declare module.exports: $Exports<'minimist/test/short'>;
}
declare module 'minimist/test/stop_early.js' {
  declare module.exports: $Exports<'minimist/test/stop_early'>;
}
declare module 'minimist/test/unknown.js' {
  declare module.exports: $Exports<'minimist/test/unknown'>;
}
declare module 'minimist/test/whitespace.js' {
  declare module.exports: $Exports<'minimist/test/whitespace'>;
}
