// flow-typed signature: 1eb8ad0d355364a8e1363f22ab0c647b
// flow-typed version: <<STUB>>/mocha_v5.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha' {
  declare module.exports: any;
}
