// flow-typed signature: fd53c7307894c0f4a6866917d63e2497
// flow-typed version: <<STUB>>/mocha_v^3.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha' {
  declare module.exports: any;
}
