// flow-typed signature: 7b6dd160c34736e67157fb29f7b988e0
// flow-typed version: <<STUB>>/mocha-in-sauce_v0.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-in-sauce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-in-sauce' {
  declare module.exports: any;
}
