// flow-typed signature: 2e5d10202182733577dd043d68f351cb
// flow-typed version: <<STUB>>/nanoid_v^1.0.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nanoid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nanoid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nanoid/format' {
  declare module.exports: any;
}

declare module 'nanoid/generate' {
  declare module.exports: any;
}

declare module 'nanoid/random-browser' {
  declare module.exports: any;
}

declare module 'nanoid/random' {
  declare module.exports: any;
}

declare module 'nanoid/url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nanoid/format.js' {
  declare module.exports: $Exports<'nanoid/format'>;
}
declare module 'nanoid/generate.js' {
  declare module.exports: $Exports<'nanoid/generate'>;
}
declare module 'nanoid/index' {
  declare module.exports: $Exports<'nanoid'>;
}
declare module 'nanoid/index.js' {
  declare module.exports: $Exports<'nanoid'>;
}
declare module 'nanoid/random-browser.js' {
  declare module.exports: $Exports<'nanoid/random-browser'>;
}
declare module 'nanoid/random.js' {
  declare module.exports: $Exports<'nanoid/random'>;
}
declare module 'nanoid/url.js' {
  declare module.exports: $Exports<'nanoid/url'>;
}
