// flow-typed signature: fe1bed9a494fa6bd8d93f91d966dfd9a
// flow-typed version: <<STUB>>/npm-scripts-info_v^0.3.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-scripts-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-scripts-info' {
  declare module.exports: any;
}
