// flow-typed signature: 6234280159bb0b8c557267e78aa20f08
// flow-typed version: <<STUB>>/npm-run-all_v^4.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-run-all'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-run-all' {
  declare module.exports: any;
}
