// flow-typed signature: f544de011209d660097a842eaa1f7461
// flow-typed version: <<STUB>>/nyc_v11.4.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nyc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nyc' {
  declare module.exports: any;
}
