// flow-typed signature: 35c47c6135fd3b4461c163886b73d573
// flow-typed version: <<STUB>>/nyc_v^10.2.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nyc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nyc' {
  declare module.exports: any;
}
