// flow-typed signature: a91a0162c0c538e7acf2a5711be05797
// flow-typed version: <<STUB>>/opn-cli_v^3.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opn-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opn-cli' {
  declare module.exports: any;
}
