// flow-typed signature: 0d3b424b7fa7876e54288c98b16e950a
// flow-typed version: <<STUB>>/opn-cli_v3.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opn-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opn-cli' {
  declare module.exports: any;
}
