// flow-typed signature: 91e0b9e438e9793baa8c8d66fc9a0a47
// flow-typed version: <<STUB>>/ora_v^3.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ora'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ora' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ora/index' {
  declare module.exports: $Exports<'ora'>;
}
declare module 'ora/index.js' {
  declare module.exports: $Exports<'ora'>;
}
