// flow-typed signature: 8d77eb0e1007f0190223f343284e383c
// flow-typed version: <<STUB>>/platform_v1.3.5/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'platform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'platform' {
  declare module.exports: any;
}
