// flow-typed signature: e654673b2f03bebba655e0e2cfafb9b8
// flow-typed version: <<STUB>>/platform_v^1.3.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'platform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'platform' {
  declare module.exports: any;
}
