// flow-typed signature: 17bf531edd1e76b75854b91db12ef1b7
// flow-typed version: <<STUB>>/promise_v^7.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise' {
  declare module.exports: any;
}
