// flow-typed signature: 3f30210ddd80609ab349e0e051ba44b0
// flow-typed version: <<STUB>>/promise_v8.0.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise' {
  declare module.exports: any;
}
