// flow-typed signature: d5fce1fc1f6baa96d4ca2f6275e6f6c5
// flow-typed version: <<STUB>>/protractor_v^3.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protractor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protractor' {
  declare module.exports: any;
}
