// flow-typed signature: d1c89b619114b55f4fc74858ca5d9483
// flow-typed version: <<STUB>>/protractor_v3.1.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protractor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protractor' {
  declare module.exports: any;
}
