// flow-typed signature: ddd80a4ce56a2a47a60cc34773a3bbfd
// flow-typed version: <<STUB>>/rollup-plugin-inject_v^2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-inject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-inject' {
  declare module.exports: any;
}
