// flow-typed signature: c4ae7b661bf3815a89adf519a44f70c0
// flow-typed version: <<STUB>>/rollup-plugin-inject_v2.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-inject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-inject' {
  declare module.exports: any;
}
