// flow-typed signature: ca8b76f858fc424cd93c06dd55c2134d
// flow-typed version: <<STUB>>/rx_vlatest/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rx' {
  declare module.exports: any;
}
