// flow-typed signature: 1c231857ce0a37e31999cdf4c50cd6a8
// flow-typed version: <<STUB>>/rx_vlatest/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rx' {
  declare module.exports: any;
}
