// flow-typed signature: 4a9410f4b1ca59e0f01e92166df7483a
// flow-typed version: <<STUB>>/shx_v^0.2.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shx' {
  declare module.exports: any;
}
