// flow-typed signature: f4f093e8dfdeb209477e4ebada3101dd
// flow-typed version: <<STUB>>/shx_v0.2.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shx' {
  declare module.exports: any;
}
