// flow-typed signature: ce0e5f920cff689d8229e78ee3c19eb3
// flow-typed version: <<STUB>>/sinon-chai_v2.14.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon-chai' {
  declare module.exports: any;
}
