// flow-typed signature: 8b07aa821aaae5acae4dd176d029fd7f
// flow-typed version: <<STUB>>/sinon_v^2.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon' {
  declare module.exports: any;
}
