// flow-typed signature: aab5858c1eafba493a182114df7355f1
// flow-typed version: <<STUB>>/sinon-chai_v^2.9.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon-chai' {
  declare module.exports: any;
}
