// flow-typed signature: 4ba1909c4c95aeee053f6ca5b119f82d
// flow-typed version: <<STUB>>/systemjs_v^0.21.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'systemjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'systemjs' {
  declare module.exports: any;
}
