// flow-typed signature: 68bc9cf8c48e7f09cfeda1c47bbd413c
// flow-typed version: <<STUB>>/tar-stream_v^2.0.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tar-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tar-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tar-stream/extract' {
  declare module.exports: any;
}

declare module 'tar-stream/headers' {
  declare module.exports: any;
}

declare module 'tar-stream/pack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tar-stream/extract.js' {
  declare module.exports: $Exports<'tar-stream/extract'>;
}
declare module 'tar-stream/headers.js' {
  declare module.exports: $Exports<'tar-stream/headers'>;
}
declare module 'tar-stream/index' {
  declare module.exports: $Exports<'tar-stream'>;
}
declare module 'tar-stream/index.js' {
  declare module.exports: $Exports<'tar-stream'>;
}
declare module 'tar-stream/pack.js' {
  declare module.exports: $Exports<'tar-stream/pack'>;
}
