// flow-typed signature: 517c2dade02adc8a8e1cf3c19dfe5e25
// flow-typed version: <<STUB>>/tar-fs_v^2.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tar-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tar-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tar-fs/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tar-fs/index' {
  declare module.exports: $Exports<'tar-fs'>;
}
declare module 'tar-fs/index.js' {
  declare module.exports: $Exports<'tar-fs'>;
}
declare module 'tar-fs/test/index.js' {
  declare module.exports: $Exports<'tar-fs/test/index'>;
}
