// flow-typed signature: 0b26d88b1a6466b1ff52f71cdfb12e3d
// flow-typed version: <<STUB>>/tsconfig-paths_v3.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tsconfig-paths'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tsconfig-paths' {
  declare module.exports: any;
}
