// flow-typed signature: 94d1c3de1e26f6b49886024c802b079c
// flow-typed version: <<STUB>>/tslint_v^4.4.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tslint' {
  declare module.exports: any;
}
