// flow-typed signature: fb47fbae6c7c791167352dbe6a3cddbc
// flow-typed version: <<STUB>>/tslint-no-unused-expression-chai_v0.0.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tslint-no-unused-expression-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tslint-no-unused-expression-chai' {
  declare module.exports: any;
}
