// flow-typed signature: 94f81470eeac533a1b2e2e6ba94c24ac
// flow-typed version: <<STUB>>/tslib_v^1.9.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tslib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tslib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tslib/tslib.es6' {
  declare module.exports: any;
}

declare module 'tslib/tslib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tslib/tslib.es6.js' {
  declare module.exports: $Exports<'tslib/tslib.es6'>;
}
declare module 'tslib/tslib.js' {
  declare module.exports: $Exports<'tslib/tslib'>;
}
