// flow-typed signature: d66157e9f0b99f272b81c0414c1f6b48
// flow-typed version: <<STUB>>/tslint_v5.9.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tslint' {
  declare module.exports: any;
}
