// flow-typed signature: 1657ed3d1f414f3318be23c9841ecb0b
// flow-typed version: <<STUB>>/typescript_v~2.0.6/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript' {
  declare module.exports: any;
}
