// flow-typed signature: 5514bc5472f14750e555ba0312fd6833
// flow-typed version: <<STUB>>/typescript_v~2.8.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript' {
  declare module.exports: any;
}
