// flow-typed signature: 9f7dcee6aff1db8e3772a1e094c472a7
// flow-typed version: <<STUB>>/validate-commit-msg_v^2.14.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'validate-commit-msg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'validate-commit-msg' {
  declare module.exports: any;
}
