// flow-typed signature: 29363db6e2e2ce7ea18e86860a8dfb42
// flow-typed version: <<STUB>>/watch_v^1.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'watch' {
  declare module.exports: any;
}
