// flow-typed signature: c3b13341e252ac4024a6cc18337010c2
// flow-typed version: <<STUB>>/webpack_v^1.13.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack' {
  declare module.exports: any;
}
