// flow-typed signature: e0a224b8f9b9cd51beede5116aabeb88
// flow-typed version: <<STUB>>/xmlhttprequest_v1.8.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xmlhttprequest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xmlhttprequest' {
  declare module.exports: any;
}
