// flow-typed signature: 9428ec637e9fda686d5a17f84c684129
// flow-typed version: <<STUB>>/xmlhttprequest_v1.8.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xmlhttprequest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xmlhttprequest' {
  declare module.exports: any;
}
