// flow-typed signature: 888aedf123f92bb0f262f2ba8da84997
// flow-typed version: <<STUB>>/@erebos/api-bzz-browser_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@erebos/api-bzz-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@erebos/api-bzz-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@erebos/api-bzz-browser/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@erebos/api-bzz-browser/src/index.js' {
  declare module.exports: $Exports<'@erebos/api-bzz-browser/src/index'>;
}
