// flow-typed signature: 81039ecd6c8fbc2d2fc2d5f323fb1cbe
// flow-typed version: <<STUB>>/@erebos/api-bzz-node_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@erebos/api-bzz-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@erebos/api-bzz-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@erebos/api-bzz-node/src/fs' {
  declare module.exports: any;
}

declare module '@erebos/api-bzz-node/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@erebos/api-bzz-node/src/fs.js' {
  declare module.exports: $Exports<'@erebos/api-bzz-node/src/fs'>;
}
declare module '@erebos/api-bzz-node/src/index.js' {
  declare module.exports: $Exports<'@erebos/api-bzz-node/src/index'>;
}
