// flow-typed signature: cb414c70616a700bbe0035c057a8abf3
// flow-typed version: <<STUB>>/@erebos/api-bzz-base_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@erebos/api-bzz-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@erebos/api-bzz-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@erebos/api-bzz-base/src/feed' {
  declare module.exports: any;
}

declare module '@erebos/api-bzz-base/src/index' {
  declare module.exports: any;
}

declare module '@erebos/api-bzz-base/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@erebos/api-bzz-base/src/feed.js' {
  declare module.exports: $Exports<'@erebos/api-bzz-base/src/feed'>;
}
declare module '@erebos/api-bzz-base/src/index.js' {
  declare module.exports: $Exports<'@erebos/api-bzz-base/src/index'>;
}
declare module '@erebos/api-bzz-base/src/types.js' {
  declare module.exports: $Exports<'@erebos/api-bzz-base/src/types'>;
}
