// flow-typed signature: 8295ba65c50e40ae812b3fa5eafc14bd
// flow-typed version: <<STUB>>/@erebos/client-base_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@erebos/client-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@erebos/client-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@erebos/client-base/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@erebos/client-base/src/index.js' {
  declare module.exports: $Exports<'@erebos/client-base/src/index'>;
}
