// flow-typed signature: 22072a81325b3751211dac2fd5e6e91a
// flow-typed version: <<STUB>>/@erebos/hex_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@erebos/hex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@erebos/hex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@erebos/hex/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@erebos/hex/src/index.js' {
  declare module.exports: $Exports<'@erebos/hex/src/index'>;
}
