// flow-typed signature: 5b8a31d85f5a60110ab6a4f7daed79dd
// flow-typed version: <<STUB>>/@erebos/keccak256_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@erebos/keccak256'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@erebos/keccak256' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@erebos/keccak256/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@erebos/keccak256/src/index.js' {
  declare module.exports: $Exports<'@erebos/keccak256/src/index'>;
}
