// flow-typed signature: 2753c889a6da98601acd3a864ad5781e
// flow-typed version: <<STUB>>/@erebos/secp256k1_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@erebos/secp256k1'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@erebos/secp256k1' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@erebos/secp256k1/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@erebos/secp256k1/src/index.js' {
  declare module.exports: $Exports<'@erebos/secp256k1/src/index'>;
}
