// flow-typed signature: b675385fe999dd402bcb9440c891d211
// flow-typed version: <<STUB>>/@erebos/swarm-node_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@erebos/swarm-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@erebos/swarm-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@erebos/swarm-node/src/Client' {
  declare module.exports: any;
}

declare module '@erebos/swarm-node/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@erebos/swarm-node/src/Client.js' {
  declare module.exports: $Exports<'@erebos/swarm-node/src/Client'>;
}
declare module '@erebos/swarm-node/src/index.js' {
  declare module.exports: $Exports<'@erebos/swarm-node/src/index'>;
}
