// flow-typed signature: 419cb2a382a9b3ea70697f2553b9d997
// flow-typed version: <<STUB>>/@erebos/swarm-browser_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@erebos/swarm-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@erebos/swarm-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@erebos/swarm-browser/rollup.config' {
  declare module.exports: any;
}

declare module '@erebos/swarm-browser/src/Client' {
  declare module.exports: any;
}

declare module '@erebos/swarm-browser/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@erebos/swarm-browser/rollup.config.js' {
  declare module.exports: $Exports<'@erebos/swarm-browser/rollup.config'>;
}
declare module '@erebos/swarm-browser/src/Client.js' {
  declare module.exports: $Exports<'@erebos/swarm-browser/src/Client'>;
}
declare module '@erebos/swarm-browser/src/index.js' {
  declare module.exports: $Exports<'@erebos/swarm-browser/src/index'>;
}
