// flow-typed signature: fa40944b719806da4dd109cde773d9c1
// flow-typed version: <<STUB>>/@mainframe/rpc-ws-node_v^0.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mainframe/rpc-ws-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mainframe/rpc-ws-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mainframe/rpc-ws-node/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mainframe/rpc-ws-node/lib/index.js' {
  declare module.exports: $Exports<'@mainframe/rpc-ws-node/lib/index'>;
}
