// flow-typed signature: b8fc636897c7f3f3aff883b068049afa
// flow-typed version: <<STUB>>/@mainframe/rpc-stream_v^0.3.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mainframe/rpc-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mainframe/rpc-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mainframe/rpc-stream/cjs/index' {
  declare module.exports: any;
}

declare module '@mainframe/rpc-stream/esm/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mainframe/rpc-stream/cjs/index.js' {
  declare module.exports: $Exports<'@mainframe/rpc-stream/cjs/index'>;
}
declare module '@mainframe/rpc-stream/esm/index.js' {
  declare module.exports: $Exports<'@mainframe/rpc-stream/esm/index'>;
}
