// flow-typed signature: 86da60493cfe9c37f15c3eda3e72620c
// flow-typed version: <<STUB>>/@mainframe/rpc-node_v^0.3.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mainframe/rpc-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mainframe/rpc-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mainframe/rpc-node/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mainframe/rpc-node/lib/index.js' {
  declare module.exports: $Exports<'@mainframe/rpc-node/lib/index'>;
}
