// flow-typed signature: 25c2617e223debc3c54f3f15a67b55bd
// flow-typed version: <<STUB>>/@mainframe/rpc-node_v^0.3.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mainframe/rpc-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mainframe/rpc-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mainframe/rpc-node/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mainframe/rpc-node/lib/index.js' {
  declare module.exports: $Exports<'@mainframe/rpc-node/lib/index'>;
}
