// flow-typed signature: 4d7aa7ecc146bc91e7a60f64d11aa7d8
// flow-typed version: <<STUB>>/@mainframe/rpc-browser_v^0.3.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mainframe/rpc-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mainframe/rpc-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mainframe/rpc-browser/cjs/index' {
  declare module.exports: any;
}

declare module '@mainframe/rpc-browser/esm/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mainframe/rpc-browser/cjs/index.js' {
  declare module.exports: $Exports<'@mainframe/rpc-browser/cjs/index'>;
}
declare module '@mainframe/rpc-browser/esm/index.js' {
  declare module.exports: $Exports<'@mainframe/rpc-browser/esm/index'>;
}
