// flow-typed signature: 69582ec171a126e8b49aa55f7fc789f8
// flow-typed version: <<STUB>>/@mainframe/rpc-web3_v^0.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mainframe/rpc-web3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mainframe/rpc-web3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mainframe/rpc-web3/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mainframe/rpc-web3/lib/index.js' {
  declare module.exports: $Exports<'@mainframe/rpc-web3/lib/index'>;
}
