// flow-typed signature: ef04899ab49c80081f18d83e4be39a09
// flow-typed version: <<STUB>>/erebos-client-base_v*/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'erebos-client-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'erebos-client-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'erebos-client-base/flow-typed/npm/erebos-api-bzz-base_vx.x.x' {
  declare module.exports: any;
}

declare module 'erebos-client-base/flow-typed/npm/erebos-api-eth_vx.x.x' {
  declare module.exports: any;
}

declare module 'erebos-client-base/flow-typed/npm/erebos-api-net_vx.x.x' {
  declare module.exports: any;
}

declare module 'erebos-client-base/flow-typed/npm/erebos-api-pss_vx.x.x' {
  declare module.exports: any;
}

declare module 'erebos-client-base/flow-typed/npm/erebos-api-shh_vx.x.x' {
  declare module.exports: any;
}

declare module 'erebos-client-base/flow-typed/npm/erebos-api-web3_vx.x.x' {
  declare module.exports: any;
}

declare module 'erebos-client-base/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'erebos-client-base/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'erebos-client-base/flow-typed/npm/erebos-api-bzz-base_vx.x.x.js' {
  declare module.exports: $Exports<'erebos-client-base/flow-typed/npm/erebos-api-bzz-base_vx.x.x'>;
}
declare module 'erebos-client-base/flow-typed/npm/erebos-api-eth_vx.x.x.js' {
  declare module.exports: $Exports<'erebos-client-base/flow-typed/npm/erebos-api-eth_vx.x.x'>;
}
declare module 'erebos-client-base/flow-typed/npm/erebos-api-net_vx.x.x.js' {
  declare module.exports: $Exports<'erebos-client-base/flow-typed/npm/erebos-api-net_vx.x.x'>;
}
declare module 'erebos-client-base/flow-typed/npm/erebos-api-pss_vx.x.x.js' {
  declare module.exports: $Exports<'erebos-client-base/flow-typed/npm/erebos-api-pss_vx.x.x'>;
}
declare module 'erebos-client-base/flow-typed/npm/erebos-api-shh_vx.x.x.js' {
  declare module.exports: $Exports<'erebos-client-base/flow-typed/npm/erebos-api-shh_vx.x.x'>;
}
declare module 'erebos-client-base/flow-typed/npm/erebos-api-web3_vx.x.x.js' {
  declare module.exports: $Exports<'erebos-client-base/flow-typed/npm/erebos-api-web3_vx.x.x'>;
}
declare module 'erebos-client-base/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'erebos-client-base/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'erebos-client-base/src/index.js' {
  declare module.exports: $Exports<'erebos-client-base/src/index'>;
}
