// flow-typed signature: 983bef359570886009e638b0f59bc44a
// flow-typed version: <<STUB>>/@angular-devkit/build-optimizer_v0.4.6/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@angular-devkit/build-optimizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@angular-devkit/build-optimizer' {
  declare module.exports: any;
}
