// flow-typed signature: 12eedcdb3fb0550d9b4f6227313ac585
// flow-typed version: <<STUB>>/@angular-devkit/build-optimizer_v0.0.24/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@angular-devkit/build-optimizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@angular-devkit/build-optimizer' {
  declare module.exports: any;
}
