// flow-typed signature: dc439562a6481ef3728b7615b80dc7ad
// flow-typed version: <<STUB>>/@angular-devkit/schematics_v^0.5.4/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@angular-devkit/schematics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@angular-devkit/schematics' {
  declare module.exports: any;
}
